title: Tran Son
author: Son Tran Van
email: sonhipkmhd@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Wow, I'm a student!

twitter_username: macrod68
github_username:  macrod68

sass:
    style: compressed